//All Responses const
export const ALL_RESPONSES = 'ALL_RESPONSES';
export const ALL_RESPONSES_LOADING = 'ALL_RESPONSES_LOADING';
export const ALL_RESPONSES_FAILED = 'ALL_RESPONSES_FAILED';
export const ALL_RESPONSES_SUCCESS = 'ALL_RESPONSES_SUCCESS';
export const ALL_RESPONSES_CLEAR = 'ALL_RESPONSES_CLEAR';

//user Responses const
export const USER_RESPONSES = 'USER_RESPONSES';
export const USER_RESPONSES_LOADING = 'USER_RESPONSES_LOADING';
export const USER_RESPONSES_FAILED = 'USER_RESPONSES_FAILED';
export const USER_RESPONSES_SUCCESS = 'USER_RESPONSES_SUCCESS';
export const USER_RESPONSES_CLEAR = 'USER_RESPONSES_CLEAR';
