//save credentials const
export const CREDENTIALS_SAVE = 'CREDENTIALS_SAVE';
export const CREDENTIALS_SAVE_LOADING = 'CREDENTIALS_SAVE_LOADING';
export const CREDENTIALS_SAVE_FAILED = 'CREDENTIALS_SAVE_FAILED';
export const CREDENTIALS_SAVE_SUCCESS = 'CREDENTIALS_SAVE_SUCCESS';
export const CREDENTIALS_SAVE_ERROR = 'CREDENTIALS_SAVE_ERROR';
//delete credentials const
export const CREDENTIALS_DELETE = 'CREDENTIALS_DELETE';
export const CREDENTIALS_DELETE_LOADING = 'CREDENTIALS_DELETE_LOADING';
export const CREDENTIALS_DELETE_FAILED = 'CREDENTIALS_DELETE_FAILED';
export const CREDENTIALS_DELETE_SUCCESS = 'CREDENTIALS_DELETE_SUCCESS';
export const CREDENTIALS_DELETE_ERROR = 'CREDENTIALS_DELETE_ERROR';
