//question const
export const CREDENTIALS_SAVE = 'CREDENTIALS_SAVE';
export const CREDENTIALS_SAVE_LOADING = 'CREDENTIALS_SAVE_LOADING';
export const CREDENTIALS_SAVE_FAILED = 'CREDENTIALS_SAVE_FAILED';
export const CREDENTIALS_SAVE_SUCCESS = 'CREDENTIALS_SAVE_SUCCESS';
export const CREDENTIALS_SAVE_ERROR = 'CREDENTIALS_SAVE_ERROR';
