//question const
export const QUESTIONS_LOADING = 'QUESTIONS_LOADING';
export const QUESTIONS_LOADING_FAILED = 'QUESTIONS_LOADING_FAILED';
export const QUESTIONS_LOADING_SUCCESS = 'QUESTIONS_LOADING_SUCCESS';
export const QUESTIONS_LOADING_ERROR = 'QUESTIONS_LOADING_ERROR';
