// submitresponses const
export const RESPONSE_SUBMIT = 'RESPONSE_SUBMIT';
export const RESPONSE_SUBMIT_LOADING = 'RESPONSE_SUBMIT_LOADING';
export const RESPONSE_SUBMIT_FAILED = 'RESPONSE_SUBMIT_FAILED';
export const RESPONSE_SUBMIT_SUCCESS = 'RESPONSE_SUBMIT_SUCCESS';
//delete responses const
export const RESPONSE_DELETE = 'RESPONSE_DELETE';
export const RESPONSE_DELETE_LOADING = 'RESPONSE_DELETE_LOADING';
export const RESPONSE_DELETE_FAILED = 'RESPONSE_DELETE_FAILED';
export const RESPONSE_DELETE_SUCCESS = 'RESPONSE_DELETE_SUCCESS';
