//question const
export const RESPONSE_SUBMIT = 'RESPONSE_SUBMIT';
export const RESPONSE_SUBMIT_LOADING = 'RESPONSE_SUBMIT_LOADING';
export const RESPONSE_SUBMIT_FAILED = 'RESPONSE_SUBMIT_FAILED';
export const RESPONSE_SUBMIT_SUCCESS = 'RESPONSE_SUBMIT_SUCCESS';
