//timer const
export const TIMER_TICK = 'TIMER_TICK';
export const TIMER_TICK_LOADING = 'TIMER_TICK_LOADING';
export const TIMER_TICK_FAILED = 'TIMER_TICK_FAILED';
export const TIMER_TICK_SUCCESS = 'TIMER_TICK_SUCCESS';

//timer const
export const TIMER_PAUSE = 'TIMER_PAUSE';
export const TIMER_PAUSE_LOADING = 'TIMER_PAUSE_LOADING';
export const TIMER_PAUSE_FAILED = 'TIMER_PAUSE_FAILED';
export const TIMER_PAUSE_SUCCESS = 'TIMER_PAUSE_SUCCESS';
